%% CRC32 crc32_le handler
%% This is part of eee_tools
%%
%% Copyright (c) 2025 Winford (Uncle Grumpy) <winford@object.stream>
%% All rights reserved.
%%
%% Licensed under the Apache License, Version 2.0 (the "License");
%% you may not use this file except in compliance with the License.
%% You may obtain a copy of the License at
%%
%%     http://www.apache.org/licenses/LICENSE-2.0
%%
%% Unless required by applicable law or agreed to in writing, software
%% distributed under the License is distributed on an "AS IS" BASIS,
%% WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
%% See the License for the specific language governing permissions and
%% limitations under the License.
%%
%% SPDX-FileCopyrightText: 2025 Winford (Uncle Grumpy) <winford@object.stream>
%% SPDX-License-Identifier: Apache-2.0 OR LGPL-2.1-or-later

%%-------------------------------------------------------------------
%% @doc Utility for generating crc32 checksums compatible with the
%% crc checksums generated by the esp32 rom crc functions.
%%
%% At the moment this module only supports crc32_le.
%% @end
%%-------------------------------------------------------------------
-module(ecrc).

-export([crc32_le/1]).

-export_type([crc32_checksum/0]).

-type crc32_checksum() :: non_neg_integer().

%%-------------------------------------------------------------------
%% @param Data to generate crc32 checksum for
%% @doc Generate a t:crc32_checksum/0 for the given data
%%
%% The checksums from this function are compatible with those generated with the ESP-IDF
%% esp_rom_crc32_le() function built into the device rom. This little endian crc32 is typically
%% uses for checksums of NVS key-value entries in the `nvs' partition.
%% @since 0.1.0
%% @end
%%-------------------------------------------------------------------
-spec crc32_le(Data :: iodata()) -> crc32_checksum().
crc32_le(Data) ->
    case erlang:system_info(machine) of
        "BEAM" ->
            erlang:crc32(16#ffffffff, Data);
        "ATOM" ->
            eee_crc32_le(Data, 16#00000000);
        Other ->
            error({unsupported_vm, Other})
    end.

%%===================================================================
%% Internal Functions
%%===================================================================

-spec eee_crc32_le(Data :: iodata(), LastCrc :: crc32_checksum()) -> crc32_checksum().
eee_crc32_le(Data, LastCrc) when is_list(Data) ->
    eee_crc32_le(list_to_binary(Data), LastCrc);
eee_crc32_le(<<>>, LastCrc) ->
    16#ffffffff band bnot LastCrc;
eee_crc32_le(<<Current:1/unsigned-integer-unit:8, Rest/binary>>, LastCrc) ->
    Index = (LastCrc bxor Current) band 16#ff,
    eee_crc32_le(Rest, crc32_le_table_lookup(Index) bxor (LastCrc bsr 8)).

crc32_le_table_lookup(0) -> 16#00000000;
crc32_le_table_lookup(1) -> 16#77073096;
crc32_le_table_lookup(2) -> 16#ee0e612c;
crc32_le_table_lookup(3) -> 16#990951ba;
crc32_le_table_lookup(4) -> 16#076dc419;
crc32_le_table_lookup(5) -> 16#706af48f;
crc32_le_table_lookup(6) -> 16#e963a535;
crc32_le_table_lookup(7) -> 16#9e6495a3;
crc32_le_table_lookup(8) -> 16#0edb8832;
crc32_le_table_lookup(9) -> 16#79dcb8a4;
crc32_le_table_lookup(10) -> 16#e0d5e91e;
crc32_le_table_lookup(11) -> 16#97d2d988;
crc32_le_table_lookup(12) -> 16#09b64c2b;
crc32_le_table_lookup(13) -> 16#7eb17cbd;
crc32_le_table_lookup(14) -> 16#e7b82d07;
crc32_le_table_lookup(15) -> 16#90bf1d91;
crc32_le_table_lookup(16) -> 16#1db71064;
crc32_le_table_lookup(17) -> 16#6ab020f2;
crc32_le_table_lookup(18) -> 16#f3b97148;
crc32_le_table_lookup(19) -> 16#84be41de;
crc32_le_table_lookup(20) -> 16#1adad47d;
crc32_le_table_lookup(21) -> 16#6ddde4eb;
crc32_le_table_lookup(22) -> 16#f4d4b551;
crc32_le_table_lookup(23) -> 16#83d385c7;
crc32_le_table_lookup(24) -> 16#136c9856;
crc32_le_table_lookup(25) -> 16#646ba8c0;
crc32_le_table_lookup(26) -> 16#fd62f97a;
crc32_le_table_lookup(27) -> 16#8a65c9ec;
crc32_le_table_lookup(28) -> 16#14015c4f;
crc32_le_table_lookup(29) -> 16#63066cd9;
crc32_le_table_lookup(30) -> 16#fa0f3d63;
crc32_le_table_lookup(31) -> 16#8d080df5;
crc32_le_table_lookup(32) -> 16#3b6e20c8;
crc32_le_table_lookup(33) -> 16#4c69105e;
crc32_le_table_lookup(34) -> 16#d56041e4;
crc32_le_table_lookup(35) -> 16#a2677172;
crc32_le_table_lookup(36) -> 16#3c03e4d1;
crc32_le_table_lookup(37) -> 16#4b04d447;
crc32_le_table_lookup(38) -> 16#d20d85fd;
crc32_le_table_lookup(39) -> 16#a50ab56b;
crc32_le_table_lookup(40) -> 16#35b5a8fa;
crc32_le_table_lookup(41) -> 16#42b2986c;
crc32_le_table_lookup(42) -> 16#dbbbc9d6;
crc32_le_table_lookup(43) -> 16#acbcf940;
crc32_le_table_lookup(44) -> 16#32d86ce3;
crc32_le_table_lookup(45) -> 16#45df5c75;
crc32_le_table_lookup(46) -> 16#dcd60dcf;
crc32_le_table_lookup(47) -> 16#abd13d59;
crc32_le_table_lookup(48) -> 16#26d930ac;
crc32_le_table_lookup(49) -> 16#51de003a;
crc32_le_table_lookup(50) -> 16#c8d75180;
crc32_le_table_lookup(51) -> 16#bfd06116;
crc32_le_table_lookup(52) -> 16#21b4f4b5;
crc32_le_table_lookup(53) -> 16#56b3c423;
crc32_le_table_lookup(54) -> 16#cfba9599;
crc32_le_table_lookup(55) -> 16#b8bda50f;
crc32_le_table_lookup(56) -> 16#2802b89e;
crc32_le_table_lookup(57) -> 16#5f058808;
crc32_le_table_lookup(58) -> 16#c60cd9b2;
crc32_le_table_lookup(59) -> 16#b10be924;
crc32_le_table_lookup(60) -> 16#2f6f7c87;
crc32_le_table_lookup(61) -> 16#58684c11;
crc32_le_table_lookup(62) -> 16#c1611dab;
crc32_le_table_lookup(63) -> 16#b6662d3d;
crc32_le_table_lookup(64) -> 16#76dc4190;
crc32_le_table_lookup(65) -> 16#01db7106;
crc32_le_table_lookup(66) -> 16#98d220bc;
crc32_le_table_lookup(67) -> 16#efd5102a;
crc32_le_table_lookup(68) -> 16#71b18589;
crc32_le_table_lookup(69) -> 16#06b6b51f;
crc32_le_table_lookup(70) -> 16#9fbfe4a5;
crc32_le_table_lookup(71) -> 16#e8b8d433;
crc32_le_table_lookup(72) -> 16#7807c9a2;
crc32_le_table_lookup(73) -> 16#0f00f934;
crc32_le_table_lookup(74) -> 16#9609a88e;
crc32_le_table_lookup(75) -> 16#e10e9818;
crc32_le_table_lookup(76) -> 16#7f6a0dbb;
crc32_le_table_lookup(77) -> 16#086d3d2d;
crc32_le_table_lookup(78) -> 16#91646c97;
crc32_le_table_lookup(79) -> 16#e6635c01;
crc32_le_table_lookup(80) -> 16#6b6b51f4;
crc32_le_table_lookup(81) -> 16#1c6c6162;
crc32_le_table_lookup(82) -> 16#856530d8;
crc32_le_table_lookup(83) -> 16#f262004e;
crc32_le_table_lookup(84) -> 16#6c0695ed;
crc32_le_table_lookup(85) -> 16#1b01a57b;
crc32_le_table_lookup(86) -> 16#8208f4c1;
crc32_le_table_lookup(87) -> 16#f50fc457;
crc32_le_table_lookup(88) -> 16#65b0d9c6;
crc32_le_table_lookup(89) -> 16#12b7e950;
crc32_le_table_lookup(90) -> 16#8bbeb8ea;
crc32_le_table_lookup(91) -> 16#fcb9887c;
crc32_le_table_lookup(92) -> 16#62dd1ddf;
crc32_le_table_lookup(93) -> 16#15da2d49;
crc32_le_table_lookup(94) -> 16#8cd37cf3;
crc32_le_table_lookup(95) -> 16#fbd44c65;
crc32_le_table_lookup(96) -> 16#4db26158;
crc32_le_table_lookup(97) -> 16#3ab551ce;
crc32_le_table_lookup(98) -> 16#a3bc0074;
crc32_le_table_lookup(99) -> 16#d4bb30e2;
crc32_le_table_lookup(100) -> 16#4adfa541;
crc32_le_table_lookup(101) -> 16#3dd895d7;
crc32_le_table_lookup(102) -> 16#a4d1c46d;
crc32_le_table_lookup(103) -> 16#d3d6f4fb;
crc32_le_table_lookup(104) -> 16#4369e96a;
crc32_le_table_lookup(105) -> 16#346ed9fc;
crc32_le_table_lookup(106) -> 16#ad678846;
crc32_le_table_lookup(107) -> 16#da60b8d0;
crc32_le_table_lookup(108) -> 16#44042d73;
crc32_le_table_lookup(109) -> 16#33031de5;
crc32_le_table_lookup(110) -> 16#aa0a4c5f;
crc32_le_table_lookup(111) -> 16#dd0d7cc9;
crc32_le_table_lookup(112) -> 16#5005713c;
crc32_le_table_lookup(113) -> 16#270241aa;
crc32_le_table_lookup(114) -> 16#be0b1010;
crc32_le_table_lookup(115) -> 16#c90c2086;
crc32_le_table_lookup(116) -> 16#5768b525;
crc32_le_table_lookup(117) -> 16#206f85b3;
crc32_le_table_lookup(118) -> 16#b966d409;
crc32_le_table_lookup(119) -> 16#ce61e49f;
crc32_le_table_lookup(120) -> 16#5edef90e;
crc32_le_table_lookup(121) -> 16#29d9c998;
crc32_le_table_lookup(122) -> 16#b0d09822;
crc32_le_table_lookup(123) -> 16#c7d7a8b4;
crc32_le_table_lookup(124) -> 16#59b33d17;
crc32_le_table_lookup(125) -> 16#2eb40d81;
crc32_le_table_lookup(126) -> 16#b7bd5c3b;
crc32_le_table_lookup(127) -> 16#c0ba6cad;
crc32_le_table_lookup(128) -> 16#edb88320;
crc32_le_table_lookup(129) -> 16#9abfb3b6;
crc32_le_table_lookup(130) -> 16#03b6e20c;
crc32_le_table_lookup(131) -> 16#74b1d29a;
crc32_le_table_lookup(132) -> 16#ead54739;
crc32_le_table_lookup(133) -> 16#9dd277af;
crc32_le_table_lookup(134) -> 16#04db2615;
crc32_le_table_lookup(135) -> 16#73dc1683;
crc32_le_table_lookup(136) -> 16#e3630b12;
crc32_le_table_lookup(137) -> 16#94643b84;
crc32_le_table_lookup(138) -> 16#0d6d6a3e;
crc32_le_table_lookup(139) -> 16#7a6a5aa8;
crc32_le_table_lookup(140) -> 16#e40ecf0b;
crc32_le_table_lookup(141) -> 16#9309ff9d;
crc32_le_table_lookup(142) -> 16#0a00ae27;
crc32_le_table_lookup(143) -> 16#7d079eb1;
crc32_le_table_lookup(144) -> 16#f00f9344;
crc32_le_table_lookup(145) -> 16#8708a3d2;
crc32_le_table_lookup(146) -> 16#1e01f268;
crc32_le_table_lookup(147) -> 16#6906c2fe;
crc32_le_table_lookup(148) -> 16#f762575d;
crc32_le_table_lookup(149) -> 16#806567cb;
crc32_le_table_lookup(150) -> 16#196c3671;
crc32_le_table_lookup(151) -> 16#6e6b06e7;
crc32_le_table_lookup(152) -> 16#fed41b76;
crc32_le_table_lookup(153) -> 16#89d32be0;
crc32_le_table_lookup(154) -> 16#10da7a5a;
crc32_le_table_lookup(155) -> 16#67dd4acc;
crc32_le_table_lookup(156) -> 16#f9b9df6f;
crc32_le_table_lookup(157) -> 16#8ebeeff9;
crc32_le_table_lookup(158) -> 16#17b7be43;
crc32_le_table_lookup(159) -> 16#60b08ed5;
crc32_le_table_lookup(160) -> 16#d6d6a3e8;
crc32_le_table_lookup(161) -> 16#a1d1937e;
crc32_le_table_lookup(162) -> 16#38d8c2c4;
crc32_le_table_lookup(163) -> 16#4fdff252;
crc32_le_table_lookup(164) -> 16#d1bb67f1;
crc32_le_table_lookup(165) -> 16#a6bc5767;
crc32_le_table_lookup(166) -> 16#3fb506dd;
crc32_le_table_lookup(167) -> 16#48b2364b;
crc32_le_table_lookup(168) -> 16#d80d2bda;
crc32_le_table_lookup(169) -> 16#af0a1b4c;
crc32_le_table_lookup(170) -> 16#36034af6;
crc32_le_table_lookup(171) -> 16#41047a60;
crc32_le_table_lookup(172) -> 16#df60efc3;
crc32_le_table_lookup(173) -> 16#a867df55;
crc32_le_table_lookup(174) -> 16#316e8eef;
crc32_le_table_lookup(175) -> 16#4669be79;
crc32_le_table_lookup(176) -> 16#cb61b38c;
crc32_le_table_lookup(177) -> 16#bc66831a;
crc32_le_table_lookup(178) -> 16#256fd2a0;
crc32_le_table_lookup(179) -> 16#5268e236;
crc32_le_table_lookup(180) -> 16#cc0c7795;
crc32_le_table_lookup(181) -> 16#bb0b4703;
crc32_le_table_lookup(182) -> 16#220216b9;
crc32_le_table_lookup(183) -> 16#5505262f;
crc32_le_table_lookup(184) -> 16#c5ba3bbe;
crc32_le_table_lookup(185) -> 16#b2bd0b28;
crc32_le_table_lookup(186) -> 16#2bb45a92;
crc32_le_table_lookup(187) -> 16#5cb36a04;
crc32_le_table_lookup(188) -> 16#c2d7ffa7;
crc32_le_table_lookup(189) -> 16#b5d0cf31;
crc32_le_table_lookup(190) -> 16#2cd99e8b;
crc32_le_table_lookup(191) -> 16#5bdeae1d;
crc32_le_table_lookup(192) -> 16#9b64c2b0;
crc32_le_table_lookup(193) -> 16#ec63f226;
crc32_le_table_lookup(194) -> 16#756aa39c;
crc32_le_table_lookup(195) -> 16#026d930a;
crc32_le_table_lookup(196) -> 16#9c0906a9;
crc32_le_table_lookup(197) -> 16#eb0e363f;
crc32_le_table_lookup(198) -> 16#72076785;
crc32_le_table_lookup(199) -> 16#05005713;
crc32_le_table_lookup(200) -> 16#95bf4a82;
crc32_le_table_lookup(201) -> 16#e2b87a14;
crc32_le_table_lookup(202) -> 16#7bb12bae;
crc32_le_table_lookup(203) -> 16#0cb61b38;
crc32_le_table_lookup(204) -> 16#92d28e9b;
crc32_le_table_lookup(205) -> 16#e5d5be0d;
crc32_le_table_lookup(206) -> 16#7cdcefb7;
crc32_le_table_lookup(207) -> 16#0bdbdf21;
crc32_le_table_lookup(208) -> 16#86d3d2d4;
crc32_le_table_lookup(209) -> 16#f1d4e242;
crc32_le_table_lookup(210) -> 16#68ddb3f8;
crc32_le_table_lookup(211) -> 16#1fda836e;
crc32_le_table_lookup(212) -> 16#81be16cd;
crc32_le_table_lookup(213) -> 16#f6b9265b;
crc32_le_table_lookup(214) -> 16#6fb077e1;
crc32_le_table_lookup(215) -> 16#18b74777;
crc32_le_table_lookup(216) -> 16#88085ae6;
crc32_le_table_lookup(217) -> 16#ff0f6a70;
crc32_le_table_lookup(218) -> 16#66063bca;
crc32_le_table_lookup(219) -> 16#11010b5c;
crc32_le_table_lookup(220) -> 16#8f659eff;
crc32_le_table_lookup(221) -> 16#f862ae69;
crc32_le_table_lookup(222) -> 16#616bffd3;
crc32_le_table_lookup(223) -> 16#166ccf45;
crc32_le_table_lookup(224) -> 16#a00ae278;
crc32_le_table_lookup(225) -> 16#d70dd2ee;
crc32_le_table_lookup(226) -> 16#4e048354;
crc32_le_table_lookup(227) -> 16#3903b3c2;
crc32_le_table_lookup(228) -> 16#a7672661;
crc32_le_table_lookup(229) -> 16#d06016f7;
crc32_le_table_lookup(230) -> 16#4969474d;
crc32_le_table_lookup(231) -> 16#3e6e77db;
crc32_le_table_lookup(232) -> 16#aed16a4a;
crc32_le_table_lookup(233) -> 16#d9d65adc;
crc32_le_table_lookup(234) -> 16#40df0b66;
crc32_le_table_lookup(235) -> 16#37d83bf0;
crc32_le_table_lookup(236) -> 16#a9bcae53;
crc32_le_table_lookup(237) -> 16#debb9ec5;
crc32_le_table_lookup(238) -> 16#47b2cf7f;
crc32_le_table_lookup(239) -> 16#30b5ffe9;
crc32_le_table_lookup(240) -> 16#bdbdf21c;
crc32_le_table_lookup(241) -> 16#cabac28a;
crc32_le_table_lookup(242) -> 16#53b39330;
crc32_le_table_lookup(243) -> 16#24b4a3a6;
crc32_le_table_lookup(244) -> 16#bad03605;
crc32_le_table_lookup(245) -> 16#cdd70693;
crc32_le_table_lookup(246) -> 16#54de5729;
crc32_le_table_lookup(247) -> 16#23d967bf;
crc32_le_table_lookup(248) -> 16#b3667a2e;
crc32_le_table_lookup(249) -> 16#c4614ab8;
crc32_le_table_lookup(250) -> 16#5d681b02;
crc32_le_table_lookup(251) -> 16#2a6f2b94;
crc32_le_table_lookup(252) -> 16#b40bbe37;
crc32_le_table_lookup(253) -> 16#c30c8ea1;
crc32_le_table_lookup(254) -> 16#5a05df1b;
crc32_le_table_lookup(255) -> 16#2d02ef8d.
